apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-v2
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
        version: v2
    spec:
      containers:
      - name: website
        image: nfcddemo.azurecr.io/cd-demo/cd-demo:6
        resources:
          requests:
            cpu: "11m"
            memory: "10Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
