apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: flux-website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: nfcddemo.azurecr.io/cd-demo/cd-demo:10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "10m"
            memory: "10Mi"
        ports:
        - containerPort: 80
