# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'New container image'
        required: true
        default: 'nfcddemo.azurecr.io/cd-demo/cd-demo:latest'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        kubectl set image deployment/website website=${{ github.event.inputs.image }}!
