# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'New container image'
        required: true
        default: 'nfcddemo.azurecr.io/cd-demo/cd-demo:latest'

jobs:
  update_app:
    runs-on: ubuntu-latest
    steps:
    - name: AZ CLI login
      run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT_ID }}
        
    - name: Get kubectl creds
      run: az aks get-credentials -n cd-demo -g continuous-delivery-demo

    - name: Update image
      run: |
        kubectl set image deployment/website website=${{ github.event.inputs.image }}
